title: UG_presentation_III
author: Lim Ting-iong
copyright: "BY-NC 4.0"
logo: logo.jpg

execute:
  execute_notebooks: auto

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/iong2k/UG_presentation_III
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

hide_input: true
